from .._resource import app
from ConfigManager import ConfigLoader
from fastapi.responses import FileResponse, HTMLResponse
from pathlib import Path

configs = ConfigLoader()

index_web_file = configs.get_config("Web.Index_Web_File", "").get_value(Path)

@app.get("/")
@app.get("/index.html")
async def index_web():
    if index_web_file.exists() and index_web_file.is_file():
        return FileResponse(index_web_file)
    else:
        # 该默认网页由AI生成
        return HTMLResponse(
            "<html>\n"
            "    <head>\n"
            "       <title>Welcome to Repeater API</title>\n"
            "    </head>\n"
            "    <style>\n"
            "        body {\n"
            "            margin: 0;\n"
            "            padding: 0;\n"
            "        }\n"
            "        .container {\n"
            "            display: flex;\n"
            "            justify-content: center;\n"
            "            align-items: center;\n"
            "            height: calc(100vh - 40px); \n"
            "            width: calc(100vw - 40px); \n"
            "            margin: 20px; \n"
            "            border-radius: 10px;\n"
            "            background: linear-gradient(to right, #667eea, #764ba2);\n"
            "            position: relative; \n"
            "            overflow: hidden; \n"
            "            box-sizing: border-box;\n"
            "        }\n"
            "        .main-title {\n"
            "            color: white;\n"
            "            font-size: 6vw;\n"
            "            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.36);\n"
            "        }\n"
            "        .triangle {\n"
            "            position: absolute;\n"
            "            opacity: 0.1; \n"
            "            filter: drop-shadow(0 0 10px rgba(0,0,0,0.3)); \n"
            "            pointer-events: none; \n"
            "            transition: all 0.5s ease; \n"
            "        }\n"
            "        .plain-link {\n"
            "            text-decoration: none;\n"
            "            color: inherit;\n"
            "        }\n"
            "    </style>\n"
            "    <body>\n"
            "        <div class=\"container\" id=\"triangles-container\">\n"
            "            <a href=\"/docs\" class=\"plain-link\">\n"
            "                <h1 class=\"main-title\">\n"
            "                    Welcome to Repeater API\n"
            "                </h1>\n"
            "            </a>\n"
            "        </div>\n"
            "        <script>\n"
            "            function calculateTriangleCount() {\n"
            "                \n"
            "                const screenArea = window.innerWidth * window.innerHeight;\n"
            "                const baseArea = 1200 * 800; \n"
            "                const baseCount = 15; \n"
            "                \n"
            "                const ratio = screenArea / baseArea;\n"
            "                let count = Math.floor(baseCount * ratio);\n"
            "                \n"
            "                count = Math.max(8, Math.min(30, count));\n"
            "                \n"
            "                return count;\n"
            "            }\n"
            "            \n"
            "            function createRandomTriangle() {\n"
            "                const container = document.getElementById('triangles-container');\n"
            "                const triangle = document.createElement('div');\n"
            "                \n"
            "                const size = Math.random() * 100 + 50; \n"
            "                const left = Math.random() * 100; \n"
            "                const top = Math.random() * 100; \n"
            "                \n"
            "                const colors = ['#ffffff', '#ff6b6b', '#4ecdc4', '#45b7d1', '#96ceb4'];\n"
            "                const randomColor = colors[Math.floor(Math.random() * colors.length)];\n"
            "                \n"
            "                triangle.className = 'triangle';\n"
            "                triangle.style.width = '0';\n"
            "                triangle.style.height = '0';\n"
            "                triangle.style.left = `${left}%`;\n"
            "                triangle.style.top = `${top}%`;\n"
            "                \n"
            "                const direction = Math.random() > 0.5 ? 'top' : 'bottom';\n"
            "                if (direction === 'top') {\n"
            "                    triangle.style.borderLeft = `${size/2}px solid transparent`;\n"
            "                    triangle.style.borderRight = `${size/2}px solid transparent`;\n"
            "                    triangle.style.borderBottom = `${size}px solid ${randomColor}`;\n"
            "                } else {\n"
            "                    triangle.style.borderLeft = `${size/2}px solid transparent`;\n"
            "                    triangle.style.borderRight = `${size/2}px solid transparent`;\n"
            "                    triangle.style.borderTop = `${size}px solid ${randomColor}`;\n"
            "                }\n"
            "                \n"
            "                triangle.style.transform = `rotate(${Math.random() * 360}deg)`;\n"
            "                \n"
            "                container.appendChild(triangle);\n"
            "            }\n"
            "            \n"
            "            \n"
            "            function createTriangles() {\n"
            "                const count = calculateTriangleCount();\n"
            "                console.log(`Creating ${count} triangles for screen size: ${window.innerWidth}x${window.innerHeight}`);\n"
            "                \n"
            "                const container = document.getElementById('triangles-container');\n"
            "                const existingTriangles = container.querySelectorAll('.triangle');\n"
            "                existingTriangles.forEach(triangle => triangle.remove());\n"
            "                \n"
            "                for (let i = 0; i < count; i++) {\n"
            "                    createRandomTriangle();\n"
            "                }\n"
            "            }\n"
            "            \n"
            "            \n"
            "            document.addEventListener('DOMContentLoaded', function() {\n"
            "                createTriangles();\n"
            "                \n"
            "                window.addEventListener('resize', function() {\n"
            "                    createTriangles();\n"
            "                });\n"
            "            });\n"
            "        </script>\n"
            "    </body>\n"
            "</html>"
        )